spring:
  application:
    name: foyer
  datasource:
    url: jdbc:mysql://localhost:3306/foyer?createDatabaseIfNotExist=true
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method
    display-request-duration: true



server:
  servlet:
    context-path: /foyer
  port: 8083